import { defineCollection, z } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

const looseStringList = z.union([z.string(), z.array(z.string())]);
const reviewDate = z.union([z.string(), z.date()]);

// QA gate mềm: chuẩn hóa metadata mới nhưng vẫn nuốt frontmatter Obsidian/vault cũ.
export const collections = {
	docs: defineCollection({
		loader: docsLoader(),
		schema: docsSchema({
			extend: z.object({
				type: z
					.enum([
						'book-chapter',
						'clinical-case',
						'treatment-update',
						'topic-index',
						'tutorial',
						'learning-path',
						'how-to-guide',
						'reference-note',
						'explanation',
						'chapter-summary',
						'quick-reference',
						'deep-explanation',
						'assessment-mcq',
						'flashcard-set',
						'case-question-set',
						'modern-disease-topic',
						'symptom-approach',
						'diagnosis-workup',
						'differential-diagnosis',
						'treatment-guide',
						'emergency-algorithm',
						'drug-monograph',
						'antibiotic-guide',
						'microbiology-pathogen',
						'pathology-note',
						'imaging-interpretation',
						'lab-interpretation',
						'clinical-case-care',
						'evidence-review',
						'procedure-skill',
						'tcm-theory',
						'tcm-classic-chapter',
						'tcm-pattern',
						'tcm-disease-name',
						'tcm-symptom-approach',
						'tcm-differential-pattern',
						'tcm-herb-monograph',
						'tcm-formula',
						'tcm-acupoint',
						'tcm-meridian',
						'tcm-method',
						'tcm-integrative-topic',
						'tcm-case',
						'tcm-safety-evidence',
						'image-atlas',
						'comparison-table',
						'flowchart-algorithm',
						'quiz-wrapper',
						'patient-education',
						'exam-review',
						'concept-map',
						'source-original',
						'algorithm',
						'drug-note',
						'template',
					])
					.optional(),
				category: z.enum(['books', 'cases', 'updates', 'topics', 'templates', 'learning-paths']).optional(),
				diataxis: z.enum(['tutorial', 'how-to', 'reference', 'explanation']).optional(),
				medicineSystem: z.enum(['modern', 'tcm', 'integrative', 'shared']).optional(),
				templateId: z.string().optional(),
				templateFamily: z.enum(['modern', 'tcm', 'shared', 'diataxis-core']).optional(),
				intendedUse: z.string().optional(),
				estimatedTime: z.string().optional(),
				prerequisites: z.unknown().optional(),
				learningOutcomes: z.unknown().optional(),
				studyPlan: z.unknown().optional(),
				assessment: z.unknown().optional(),
				specialty: looseStringList.optional(),
				difficulty: z.enum(['beginner', 'intermediate', 'advanced']).optional(),
				status: z.unknown().optional(),
				lastReviewed: reviewDate.optional(),
				evidence_level: z.string().optional(),
				purpose: z.string().optional(),
				aliases: z.array(z.string()).optional(),
				source: z.unknown().optional(),
				sourceType: z
					.enum(['textbook', 'guideline', 'rct', 'meta-analysis', 'expert-opinion', 'raw-note'])
					.optional(),
				sourceDetail: z.string().optional(),
				sourceUrl: z.string().url().optional(),
				source_kb: z.unknown().optional(),
				nguon_KB: z.unknown().optional(),
				chunk_nguon: z.unknown().optional(),
				author: z.unknown().optional(),
				chapter: z.unknown().optional(),
				tay_y_tuong_duong: z.unknown().optional(),
				created: z.unknown().optional(),
				tags: z.unknown().optional(),
			}),
		}),
	}),
};
